### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by jim-rosales** [Bastonje/bastonje.github.io#6]
Grade: Exceeds Expectations

Summary:
Congrats on finishing your capstone project! Overall you did a fantastic job all throughout. I loved the scrollable feature you added to one of your sections and the various hover effects you added as well. The color scheme you chose was also suitable for the type of website you were building. Code wise your whole project was perfect as I didn't see any errors throughout. 

As extra practice consider researching [variables](https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_variables) and seeing if you can make use of them in this project. They are a great tool that not only improves the readability of your file but its maintainability as well.

**Comment by Bastonje** [comment]
Thank you for the review and I'm glad you liked the scroll feature! It took me quite some time and trial and error to get that right.
